
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Head from "next/head";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stay klin",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/public/pixelcomp.ico "/>
      </Head>
      <body className={inter.className}>
        <div className='container mx-auto px-8'>
        <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
